services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - nerv-network

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always
    networks:
      - nerv-network

networks:
  nerv-network:
    driver: bridge
